name: Hugo Build and Deploy

on:
  push:
    branches:
      - deploy

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages" # Allow one concurrent deployment, skip runs queued between in-progress and latest
  cancel-in-progress: false # Allow in-progress to complete

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0

    steps:
      - name: Checkout deploy branch and submodules
        uses: actions/checkout@v4
        with:
          ref: deploy # Always checkout deploy branch
          fetch-depth: 0 # Fetch full history to avoid shallow clone issues
          submodules: recursive

      - name: Install Hugo # Install Hugo CLI, Dart Sass, Node.js dependencies
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          sudo snap install dart-sass
          "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
